### ISSUE TITLE
Error 400, a message when click on profile name

### ISSUE THREAD

**Issue by kuvakina** [LeedsCC/Helm-PHR-Project#100]
In Helm-dev:

When clicking on the user's name second time here: https://www.screencast.com/t/2O1eNRuwr , user get message "Error 400: MicroService incorrectly defined for destination: mpi_service".

See in video: https://www.screencast.com/t/2tBgopJ1u

@DmitrySolyannik could you please look at this in the first instance?

**Comment by BogdanScherban** [comment]
@kuvakina 

The reason is that user profile page is unavailable in Helm version. When user click on name in User Panel, it should redirect him to the /profile page. But if this page is unavailable, user will be redirected to the homepage (with charts).

I fixed this issue and created PR:
https://github.com/PulseTile/PulseTile-React-Core/pull/303

**Comment by kuvakina** [comment]
@PhilBarrett @tony-shannon can we close this issue?
