### ISSUE TITLE
Addition of home button 

### ISSUE THREAD

**Issue by PhilBarrett** [LeedsCC/Helm-PHR-Project#13]
Add home button to top left replacing back button, as a configurable option alongside back button

**Comment by PhilBarrett** [comment]
Expect the solution to come from React Core codebase

**Comment by simongamester** [comment]
Discussed adding a config variable to themes.config.js to contain a string which defines the behaviour of the button in the top left of the header when viewing a patient record - something like 'patientTopLeftButtonBehaviour'. This could either be:

1. 'back' - Display a back button which calls location.history(-1) (mimics the browser back functionality.
2. 'home' - Returns user to their patient dashboard.

**Comment by simongamester** [comment]
I've spoken to Bogdan about this and reviewed my code to implement this.
Bogdan and I have decided to hand over the final part of this back to him, as he has an idea on how to aquire the nhs number in a cleaner way than what was proposed.

In an earlier issue for the User Tour, Bogdan required the url for the patient summary and we'd like this method to be shared by both components of the UI.

We will also revise the logic for the back and home buttons so that the presence of these buttons is defined within the theme config file.

Home Button - Will be displayed when a boolean config variable called isShowHomeBtn within themes.config is set to true.

Back Button - Will be displayed when a boolean config variable called isShowBackBtn within themes.config is set to true.

We currently have another variable called isShowPreviousBtn which is set within TopHeader.js and determines whether the top left button should be displayed at all. This returns true when the user it not on the root url or on the charts page (only applicable to IDCR installs). The display rules for the home and back buttons should be nested within this rule we well i.e.

    // If isShowPreviousBtn == true
    
        // If isShowHomeBtn == true
            SHOW HOME BUTTON (clicks through to patient summary)

        // If isShowBackBtn == true
            SHOW BACK BUTTON (clicks through to previous page)

    // Else if isSHowPreviousBtn == false

       DONT SHOW ANY BUTTONS

Bogdan, please let me know if this needs further clarification.

**Comment by simongamester** [comment]
Hi @tony-shannon Just been talking to Bogdan about this issue. He's implemented the logic above, but we started thinking about how this might impact IDCR instances.

In the above, we've got two buttons (home and back) and a variable to set each of them. The location of the home button however will always be to the patient record. 

We can either:

1. Change this so it goes to the Charts view for IDCR users and Patient Summary for PHR users.
2. Add a third button which goes to Charts and set up another matching config variable to decide if this should be used.

Option 2 would mean it would be possible to display 3 buttons in the top left if all 3 variables were set and the user was IDCR: Home, Back and Charts.

Let me know your thoughts on this.

Regards,

Simon

**Comment by tony-shannon** [comment]
> Change this so it goes to the Charts view for IDCR users and Patient Summary for PHR users.
Suggest option 1 would be good for now
thanks @simongamester 
T

**Comment by BogdanScherban** [comment]
The following changes were done:
1) Added possibility to show Home button OR/AND Back button depends on theme settings;
2) Added settings for Home and Back buttons to the theme settings config file;
3) PageURL and Homepage definition was moved to component, because it will be used in two places:
- in Home button;
- in UserPanel (for UserTour).
4) Added homepage link definition depends on User role (root page for IDCR and PatientSummary for PHR);
5) Updated unit-tests for TopHeader component.

**Comment by PhilBarrett** [comment]
Linked to 

Resolved RippleOSI/Helm-PHR-Generator#22
Resolved PulseTile-Plugins/Plugin-React-UserTour#8
Resolved PulseTile/PulseTile-React-Core#243
