### ISSUE TITLE
Mobile experience - iOS logout errors

### ISSUE THREAD

**Issue by PhilBarrett** [LeedsCC/Helm-PHR-Project#47]
Logging out produces error and doesn't return to login page

![Screen Shot 2018-10-16 at 09.46.04.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f56b7191a378e60c2f57415f4abe5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5f34aa984ecb51f043e04850a51a3165f43b.png)
![Screen Shot 2018-10-16 at 09.46.11.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f56b7191a378e60c2f57415e4fbe5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5c33aa984ecb51f043e04850a6113062f43b.png)

**Comment by PhilBarrett** [comment]
Might be as redirecting to http rather than https

**Comment by BogdanScherban** [comment]
Logout process consists of following steps:
1) Send logout request to /api/logout
2) Take success responce
3) Extract redirectURL =  'payload.redirectURL.payload' from responce
4) Clear COOKIE
5) Redirect to redirectURL.

Request /api/logout doesn't work locally without adding "http://dev.ripple.foundation:8000" and "Authorization: 'Bearer '+token"

redirectURL in local-machine is dev.ripple.foundation:8000

**Comment by simongamester** [comment]
@kuvakina Do you know if this is still an issue? Has anyone been able to replicate on login.myhelm?

**Comment by kuvakina** [comment]
@simongamester yes, it's still present (you can see it on the video): https://www.screencast.com/t/bbQJJXe36

Also, after you got error msg, if you delete /openid/session/end and reload a page, you'd go on Patient Summary page

**Comment by PhilBarrett** [comment]
@Alena1508 @kuvakina Could you take a look at this one please?

**Comment by Alena1508** [comment]
@tony-shannon  @PhilBarrett 

I'm currently looking  into this problem. 

I've found that it happens only safari browser, both for mobile and web and only for myHelm.

I'm searching for solution and tried a few things: 

1) to turn off secure cookies  in privacy settings in Safari, but it didn't
solve the problem. 

2) to add the csrf information to the header of the  requests (currently looking how to implement this)

**Comment by Alena1508** [comment]
I founded several variants to solve this problem (they are stated above). 
But I couldn't fully see if the problem was solved or not, because locally and on dev.ripple.foundation:8000 it works. 

"The “Invalid or missing CSRF token” message means that browser couldn’t create a secure cookie, or couldn’t access that cookie to authorize the login. This can be caused by ad- or script-blocking plugins, but also by the browser itself if it's not allowed to set cookies." - this is what that problem means. I cleaned cookies, but it didn't help. 

I think maybe problem is on backend side, because all works without bugs on our local machines and on 8000. 

Could you ask Rob to check it please?

@PhilBarrett @tony-shannon

**Comment by kuvakina** [comment]
as Phil mentioned, we think the problem with redirecting to http rather than https. There are security issues with Safari browser.

Because stage.myhelm.org is using https, but local machine and 8000 using htttp.

**Comment by kuvakina** [comment]
This issue was fixed by Rob. 
The problem was with logour form redirecting to http rather than https, as Phil mentioned, and it was related to the OpenId Connect server.

After tests in Safari browser (both web and mobile), logout is working correctly.

@tony-shannon @PhilBarrett Can we consider this task as Done?
