### ISSUE TITLE
Extra demographics API call

### ISSUE THREAD

**Issue by PhilBarrett** [LeedsCC/Helm-PHR-Project#65]

**Comment by BogdanScherban** [comment]
The issue has been solved.

I found a reason of twice demographics request. The reason was sending of this request in two places in the code. I removed one of them and check work of application by unit-tests

You can see that demographics request is sent one time (instead of two as earlier):
![imag111111111111111111e](https://user-images.githubusercontent.com/39263134/47853348-23a50000-dde7-11e8-863a-81105a0d8ebb.png)

**Comment by kuvakina** [comment]
Please see #280 https://waffle.io/RippleOSI/combined-development-view/cards/5bd9a6281f6d42002502bcb9

@tony-shannon @PhilBarrett

**Comment by PhilBarrett** [comment]
Thanks @kuvakina happy for this to be closed.
