### ISSUE TITLE
NGINX change investigation

### ISSUE THREAD

**Issue by PhilBarrett** [LeedsCC/Helm-PHR-Project#92]
Investigate impact of making following NGINX changes in Dev

 -    add_header Content-Security-Policy "default-src 'self'; frame-ancestors 'self'";
 - add_header Feature-Policy "geolocation none;midi none;notifications none;push none;sync-xhr none;microphone none;camera none;magnetometer none;gyroscope none;speaker self;vibrate none;fullscreen self;payment none;";
 - add_header Referrer-Policy "no-referrer-when-downgrade";
 - Check the headers in the NGINX config on the current dev setupto see if there's anything else causing problems (eg this header was added some time ago: add_header X-Frame-Options SAMEORIGIN;)

**Comment by DmitrySolyannik** [comment]
Hello Guys, I've added new headers to helm-dev server , but I changed them because I had an errors.
1) Now Content-Security-Policy : 
Content-Security-Policy “default-src ‘self’; frame-ancestors ‘self’; img-src ‘self’ data:; font-src ‘self’ data: https://use.fontawesome.com; style-src * data: ‘self’ ‘unsafe-inline’ ; script-src * data: ‘self’ ‘unsafe-inline’“;
If I am not add options like "img-src ‘self’ data:" , our application will not work, because it has no access to images, fonts, styles and scripts, also I've added "font-src ‘self’ data: https://use.fontawesome.com;" because on OpenID MS we are using external link with fonts.
2) Also I've changed Feature-Policy because there is no option like notifications and please check browser compatibility, because not all browsers have this headers right now. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy#Browser_compatibility
3) No problems with Referrer-Policy
As I said you can check it on https://helm-dev.ripple.foundation

**Comment by PhilBarrett** [comment]
@DmitrySolyannik Thanks for the update, can you consider how these images are brought into the application please, as the external source appears to be blocked due to the policy implementation

**Comment by DmitrySolyannik** [comment]
@PhilBarrett, Images already on the server, but fonts for OpenID MS has external source, I will upload those fonts and will add it to the project

**Comment by PhilBarrett** [comment]
Thanks @DmitrySolyannik

**Comment by PhilBarrett** [comment]
This needs migrating onto the latest QEWD-Up version of QEWD-Courier  please @DmitrySolyannik

**Comment by kuvakina** [comment]
Dima added to original version of QEWD (old), but not added to new version because for right now we are not using NGINX, btw I think we should create new tasks for nginx proxies to microservices

**Comment by PhilBarrett** [comment]
We are using NGINX with Helm - Please can you clarify @kuvakina

**Comment by DmitrySolyannik** [comment]
@PhilBarrett , No we are not using NGINX right now, we should setup it for QEWD.
It worked in previous version (QEWD Original version)

**Comment by PhilBarrett** [comment]
@DmitrySolyannik we need to get the NGINX config changes on the Helm-dev environment, working with the latest version of QEWD Courier please.

**Comment by tony-shannon** [comment]
thanks, can we also check to ensure these related header issues detailed above have been resolved @DmitrySolyannik on helm-dev

**Comment by DmitrySolyannik** [comment]
@PhilBarrett , @tony-shannon , I've added nginx with ssl and security headers on helm-dev, showcase and nes-dev servers. Also added changes in configs for new MS (respectForms, mpi_service).  For now it works without separate docker container with nginx. Nginx installed for each server directly. In future I need update nginx container because configs has changed and also new microservices were added.

**Comment by tony-shannon** [comment]
after d/w Dima we can confirm these settings have been updated on helm-dev

**Comment by PhilBarrett** [comment]
@robtweed we need to deploy these onto Helm Staging  and test before moving onto Helm Production

**Comment by PhilBarrett** [comment]
@robtweed  can you confirm that the NGINX changes have been applied to Staging / Production please

**Comment by tony-shannon** [comment]
@DmitrySolyannik  to check diff between Helm-dev & Helm-staging env, link with Rob if needs be
We will pass back to Rob & Eric

**Comment by PhilBarrett** [comment]
@DmitrySolyannik - from your earlier work (summarised below) please could you provide the final add_header directives for these three issues.

**Issue 1 investigation - add_header Content-Security-Policy "default-src 'self'; frame-ancestors 'self'";**

Changes made to Content-Security-Policy
Content-Security-Policy “default-src ‘self’; frame-ancestors ‘self’; img-src ‘self’ data:; font-src ‘self’ data: https://use.fontawesome.com; style-src  data: ‘self’ ‘unsafe-inline’ ; script-src  data: ‘self’ ‘unsafe-inline’“;

If we do not add options like "img-src ‘self’ data:" , our application will not work, because it has no access to images, fonts, styles and scripts, also I've added "font-src ‘self’ data: https://use.fontawesome.com;" because on OpenID MS we are using external link with fonts.

Now we’re not using the OpenID MS, may not be an issue anyway but has been applied to all builds anyway. Fonts brought internally as with images

**Issue 2 investigation add_header Feature-Policy "geolocation none;midi none;notifications none;push none;sync-xhr none;microphone none;camera none;magnetometer none;gyroscope none;speaker self;vibrate none;fullscreen self;payment none;";**

Reapply and add:

Also I've changed Feature-Policy because there is no option like notifications and please check browser compatibility, because not all browsers have this headers right now. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy#Browser_compatibility


**Issue 3 investigation - add_header Referrer-Policy "no-referrer-when-downgrade";**

No issue found, please can you re apply in staging for testing

**Comment by DmitrySolyannik** [comment]
@PhilBarrett , @tony-shannon , @robtweed 
Here is NGINX headers that I've added on helm-dev and other dev servers:

add_header Content-Security-Policy "default-src 'self'; frame-ancestors 'self'; img-src 'self' data:; font-src 'self' data:; style-src  data: 'self' 'unsafe-inline'; script-src  data: 'self' 'unsafe-inline'";
    add_header Feature-Policy "geolocation 'none';midi 'none';sync-xhr 'none';microphone 'none';camera 'none';magnetometer 'none';gyroscope 'none';speaker 'none';fullscreen 'none';payment 'none';";
    add_header Referrer-Policy "no-referrer-when-downgrade";

**Comment by DmitrySolyannik** [comment]
@PhilBarrett , @tony-shannon , @robtweed 
Here is a difference between NGINX  configs
Left one is **Helm-Dev**, right one is **Staging**
https://www.diffchecker.com/D2BBjr4S

**Comment by PhilBarrett** [comment]
Applied on Staging and tested working fine
